export const turkiyeProvinceDistricts: Record<string, string[]> = {
  'Adana': ['Aladag', 'Ceyhan', 'Cukurova', 'Feke', 'Imamoglu', 'Karaisali', 'Karatas', 'Kozan', 'Pozanti', 'Saimbeyli', 'Sariçam', 'Seyhan', 'Tufanbeyli', 'Yumurtalik', 'Yuregir'],
  'Adiyaman': ['Besni', 'Celikhan', 'Gerger', 'Golbasi', 'Kahta', 'Merkez', 'Samsat', 'Sincik', 'Tut'],
  'Afyonkarahisar': ['Basmakci', 'Bayat', 'Bolvadin', 'Cay', 'Cobanlar', 'Dazkiri', 'Dinar', 'Emirdag', 'Evciler', 'Hocalar', 'Ihsaniye', 'Iscehisar', 'Kiziloren', 'Merkez', 'Sandikli', 'Sinanpasa', 'Suhut', 'Sultandagi'],
  'Agri': ['Diyadin', 'Dogubayazit', 'Eleskirt', 'Hamur', 'Merkez', 'Patnos', 'Taslicay', 'Tutak'],
  'Aksaray': ['Agacoren', 'Eskil', 'Gulagac', 'Guzelyurt', 'Merkez', 'Ortakoy', 'Sariyahsi', 'Sultanhanı'],
  'Amasya': ['Goynucek', 'Gumushacikoy', 'Hamamozu', 'Merkez', 'Merzifon', 'Suluova', 'Tasova'],
  'Ankara': ['Akyurt', 'Altindag', 'Ayas', 'Bala', 'Beypazari', 'Camlidere', 'Cankaya', 'Cubuk', 'Elmadag', 'Etimesgut', 'Evren', 'Golbasi', 'Gudul', 'Haymana', 'Kahramankazan', 'Kalecik', 'Kecioren', 'Kizilcahamam', 'Mamak', 'Nallihan', 'Polatli', 'Pursaklar', 'Sincan', 'Sereflikochisar', 'Yenimahalle'],
  'Antalya': ['Akseki', 'Aksu', 'Alanya', 'Demre', 'Dosemealti', 'Elmali', 'Finike', 'Gazipasa', 'Gundogmus', 'Ibradi', 'Kas', 'Kemer', 'Kepez', 'Konyaalti', 'Korkuteli', 'Kumluca', 'Manavgat', 'Muratpasa', 'Serik'],
  'Ardahan': ['Cildir', 'Damal', 'Gole', 'Hanak', 'Merkez', 'Posof'],
  'Artvin': ['Ardanuc', 'Arhavi', 'Borcka', 'Hopa', 'Kemalpasa', 'Merkez', 'Murgul', 'Savsat', 'Yusufeli'],
  'Aydin': ['Bozdogan', 'Buharkent', 'Cine', 'Didim', 'Efeler', 'Germencik', 'Incirliova', 'Karacasu', 'Karpuzlu', 'Kocarli', 'Kosk', 'Kusadasi', 'Kuyucak', 'Nazilli', 'Soke', 'Sultanhisar', 'Yenipazar'],
  'Balikesir': ['Altieylul', 'Ayvalik', 'Balya', 'Bandirma', 'Bigadic', 'Burhaniye', 'Dursunbey', 'Edremit', 'Erdek', 'Gomec', 'Gonen', 'Havran', 'Ivrindi', 'Karesi', 'Kepsut', 'Manyas', 'Marmara', 'Savaştepe', 'Sindirgi', 'Susurluk'],
  'Bartin': ['Amasra', 'Kurucasile', 'Merkez', 'Ulus'],
  'Batman': ['Besiri', 'Gercus', 'Hasankeyf', 'Kozluk', 'Merkez', 'Sason'],
  'Bayburt': ['Aydintepe', 'Demirozu', 'Merkez'],
  'Bilecik': ['Bozuyuk', 'Golpazari', 'Inhisar', 'Merkez', 'Osmaneli', 'Pazaryeri', 'Sogut', 'Yenipazar'],
  'Bingol': ['Adakli', 'Genc', 'Karliova', 'Kigi', 'Merkez', 'Solhan', 'Yayladere', 'Yedisu'],
  'Bitlis': ['Adilcevaz', 'Ahlat', 'Guroymak', 'Hizan', 'Merkez', 'Mutki', 'Tatvan'],
  'Bolu': ['Dortdivan', 'Gerede', 'Goynuk', 'Kibriscik', 'Mengen', 'Merkez', 'Mudurnu', 'Seben', 'Yenicaga'],
  'Burdur': ['Aglasun', 'Altinyayla', 'Bucak', 'Cavdir', 'Celtikci', 'Golhisar', 'Karamanli', 'Kemer', 'Merkez', 'Tefenni', 'Yesilova'],
  'Bursa': ['Buyukorhan', 'Gemlik', 'Gursu', 'Harmancik', 'Inegol', 'Iznik', 'Karacabey', 'Keles', 'Kestel', 'Mudanya', 'Mustafakemalpasa', 'Nilufer', 'Orhaneli', 'Orhangazi', 'Osmangazi', 'Yenisehir', 'Yildirim'],
  'Canakkale': ['Ayvacik', 'Bayramic', 'Biga', 'Bozcaada', 'Can', 'Eceabat', 'Ezine', 'Gelibolu', 'Gokceada', 'Lapseki', 'Merkez', 'Yenice'],
  'Cankiri': ['Atkaracalar', 'Bayramoren', 'Cerkes', 'Eldivan', 'Ilgaz', 'Kizilirmak', 'Korgun', 'Kursunlu', 'Merkez', 'Orta', 'Sabanozu', 'Yaprakli'],
  'Corum': ['Alaca', 'Bayat', 'Bogazkale', 'Dodurga', 'Iskilip', 'Kargi', 'Lacin', 'Mecitozu', 'Merkez', 'Oguzlar', 'Ortakoy', 'Osmancik', 'Sungurlu', 'Ugurludag'],
  'Denizli': ['Acipayam', 'Babadag', 'Baklan', 'Bekilli', 'Beyagac', 'Bozkurt', 'Buldan', 'Cal', 'Cameli', 'Cardak', 'Civril', 'Guney', 'Honaz', 'Kale', 'Merkezefendi', 'Pamukkale', 'Saraykoy', 'Serinhisar', 'Tavas'],
  'Diyarbakir': ['Baglar', 'Bismil', 'Cermik', 'Cinar', 'Cungus', 'Dicle', 'Egil', 'Ergani', 'Hani', 'Hazro', 'Kayapinar', 'Kocakoy', 'Kulp', 'Lice', 'Silvan', 'Sur', 'Yenisehir'],
  'Duzce': ['Akcakoca', 'Cumayeri', 'Cilimli', 'Golyaka', 'Gumusova', 'Kaynasli', 'Merkez', 'Yigilca'],
  'Edirne': ['Enez', 'Havsa', 'Ipsala', 'KesAN', 'Lalapasa', 'Meric', 'Merkez', 'Suloglu', 'Uzunkopru'],
  'Elazig': ['Agin', 'Alacakaya', 'Aricak', 'Baskil', 'Karakoçan', 'Keban', 'Kovancilar', 'Maden', 'Merkez', 'Palu', 'Sivrice'],
  'Erzincan': ['Cayirli', 'Ilic', 'Kemah', 'Kemaliye', 'Merkez', 'Otlukbeli', 'Refahiye', 'Tercan', 'Uzumlu'],
  'Erzurum': ['Askale', 'Aziziye', 'Cat', 'Hinis', 'Horasan', 'Ispir', 'Karacoban', 'Karayazi', 'Karaçoban', 'Koprukoy', 'Narman', 'Oltu', 'Olur', 'Palandoken', 'Pasinler', 'Pazaryolu', 'Senkaya', 'Tekman', 'Tortum', 'Uzundere', 'Yakutiye'],
  'Eskisehir': ['Alpu', 'Beylikova', 'Cifteler', 'Gunyuzu', 'Han', 'Inonu', 'Mahmudiye', 'Mihalgazi', 'Mihaliccik', 'Odunpazari', 'Sarıcakaya', 'Seyitgazi', 'Sivrihisar', 'Tepebasi'],
  'Gaziantep': ['Araban', 'Islahiye', 'Karkamis', 'Nizip', 'Nurdagi', 'Oguzeli', 'Sahinbey', 'Sehitkamil', 'Yavuzeli'],
  'Giresun': ['Alucra', 'Bulancak', 'Camoluk', 'Canakci', 'Dereli', 'Dogankent', 'Espiye', 'Eynesil', 'Gorele', 'Guce', 'Kesap', 'Merkez', 'Piraziz', 'Sebinkarahisar', 'Tirebolu', 'Yaglidere'],
  'Gumushane': ['Kelkit', 'Kose', 'Kurtun', 'Merkez', 'Siran', 'Torul'],
  'Hakkari': ['Cukurca', 'Derecik', 'Merkez', 'Semdinli', 'Yuksekova'],
  'Hatay': ['Altinozu', 'Antakya', 'Arsuz', 'Belen', 'Defne', 'Dortyol', 'Erzin', 'Hassa', 'Iskenderun', 'Kirikhan', 'Kumlu', 'Payas', 'Reyhanli', 'Samandag', 'Yayladagi'],
  'Igdir': ['Aralik', 'Karakoyunlu', 'Merkez', 'Tuzluca'],
  'Isparta': ['Aksu', 'Atabey', 'Egirdir', 'Gelendost', 'Gonen', 'Keciborlu', 'Merkez', 'Senirkent', 'Sutculer', 'Sarkikaraagac', 'Uluborlu', 'Yalvac', 'Yenişarbademli'],
  'Istanbul': ['Adalar', 'Arnavutkoy', 'Atasehir', 'Avcilar', 'Bagcilar', 'Bahcelievler', 'Bakirkoy', 'Basaksehir', 'Bayrampasa', 'Besiktas', 'Beykoz', 'Beylikduzu', 'Beyoglu', 'Buyukcekmece', 'Catalca', 'Cekmekoy', 'Esenler', 'Esenyurt', 'Eyupsultan', 'Fatih', 'Gaziosmanpasa', 'Gungoren', 'Kadikoy', 'Kagithane', 'Kartal', 'Kucukcekmece', 'Maltepe', 'Pendik', 'Sancaktepe', 'Sariyer', 'Silivri', 'Sultanbeyli', 'Sultangazi', 'Sile', 'Sisli', 'Tuzla', 'Umraniye', 'Uskudar', 'Zeytinburnu'],
  'Izmir': ['Aliaga', 'Balcova', 'Bayindir', 'Bayrakli', 'Bergama', 'Beydag', 'Bornova', 'Buca', 'Cesme', 'Cigli', 'Dikili', 'Foca', 'Gaziemir', 'Guzelbahce', 'Karabaglar', 'Karaburun', 'Karsiyaka', 'Kemalpasa', 'Kinik', 'Kiraz', 'Konak', 'Menderes', 'Menemen', 'Narlidere', 'Odemis', 'Seferihisar', 'Selcuk', 'Tire', 'Torbali', 'Urla'],
  'Kahramanmaras': ['Afsin', 'Andirin', 'Caglayancerit', 'Dulkadiroglu', 'Ekinözu', 'Elbistan', 'Goksun', 'Nurhak', 'Onikisubat', 'Pazarcik', 'Turkoglu'],
  'Karabuk': ['Eflani', 'Eskipazar', 'Merkez', 'Ovacik', 'Safranbolu', 'Yenice'],
  'Karaman': ['Ayranci', 'Basyayla', 'Ermenek', 'Kazimkarabekir', 'Merkez', 'Sariveliler'],
  'Kars': ['Akyaka', 'Arpacay', 'Digor', 'Kagizman', 'Merkez', 'Sarıkamış', 'Selim', 'Susuz'],
  'Kastamonu': ['Abana', 'Agli', 'Arac', 'Azdavay', 'Bozkurt', 'Cide', 'Catalzeytin', 'Daday', 'Devrekani', 'Doganyurt', 'Hanonu', 'Ihsangazi', 'Inebolu', 'Kure', 'Merkez', 'Pinarbasi', 'Seydiler', 'Senpazar', 'Taskopru', 'Tosya'],
  'Kayseri': ['Akkisla', 'Bunyan', 'Develi', 'Felahiye', 'Hacilar', 'Incesu', 'Kocasinan', 'Melikgazi', 'Ozvatan', 'Pinarbasi', 'Sarioglan', 'Sariz', 'Talas', 'Tomarza', 'Yahyali', 'Yesilhisar'],
  'Kilis': ['Elbeyli', 'Merkez', 'Musabeyli', 'Polateli'],
  'Kirikkale': ['Bahsili', 'Baliseyh', 'Celebi', 'Delice', 'Karakecili', 'Keskin', 'Merkez', 'Sulakyurt', 'Yahsihan'],
  'Kirklareli': ['Babaeski', 'Demirkoy', 'Kofcaz', 'Luleburgaz', 'Merkez', 'Pehlivankoy', 'Pinarhisar', 'Vize'],
  'Kirsehir': ['Akcakent', 'Akpinar', 'Boztepe', 'Cicekdagi', 'Kaman', 'Merkez', 'Mucur'],
  'Kocaeli': ['Basiskele', 'Cayirova', 'Darica', 'Derince', 'Dilovasi', 'Gebze', 'Golcuk', 'Izmit', 'Kandira', 'Karamursel', 'Kartepe', 'Korfez'],
  'Konya': ['Ahirli', 'Akoren', 'Aksehir', 'Altinekin', 'Beysehir', 'Bozkir', 'Cihanbeyli', 'Celtik', 'Cumra', 'Derbent', 'Derebucak', 'Doganhisar', 'Emirgazi', 'Eregli', 'Guneysinir', 'Hadim', 'Halkapinar', 'Huyuk', 'Ilgin', 'Kadinhani', 'Karapinar', 'Karatay', 'Kulu', 'Meram', 'Sarayonu', 'Selcuklu', 'Seydisehir', 'Taskent', 'Tuzlukcu', 'Yalihuyuk', 'Yunak'],
  'Kutahya': ['Altintas', 'Aslanapa', 'Cavdarhisar', 'Domaniç', 'Dumlupinar', 'Emet', 'Gediz', 'Hisarcik', 'Merkez', 'Pazarlar', 'Simav', 'Saphane', 'Tavsanli'],
  'Malatya': ['Akcadag', 'Arapgir', 'Arguvan', 'Battalgazi', 'Darende', 'Dogansehir', 'Doganyol', 'Hekimhan', 'Kale', 'Kuluncak', 'Poturge', 'Yazihan', 'Yesilyurt'],
  'Manisa': ['Ahmetli', 'Akhisar', 'Alasehir', 'Demirci', 'Golmarmara', 'Gordes', 'Kirkagac', 'Koprubasi', 'Kula', 'Salihli', 'Sarigol', 'Saruhanli', 'Selendi', 'Soma', 'Sehzadeler', 'Turgutlu', 'Yunusemre'],
  'Mardin': ['Artuklu', 'Dargecit', 'Derik', 'Kiziltepe', 'Mazidagi', 'Midyat', 'Nusaybin', 'Omerli', 'Savur', 'Yesilli'],
  'Mersin': ['Akdeniz', 'Anamur', 'Aydincik', 'Bozyazi', 'Camliyayla', 'Erdemli', 'Gulnar', 'Mezitli', 'Mut', 'Silifke', 'Tarsus', 'Toroslar', 'Yenisehir'],
  'Mugla': ['Bodrum', 'Dalaman', 'Datca', 'Fethiye', 'Kavaklidere', 'Koycegiz', 'Marmaris', 'Mentese', 'Milas', 'Ortaca', 'Seydikemer', 'Ula', 'Yatagan'],
  'Mus': ['Bulanik', 'Haskoy', 'Korkut', 'Malazgirt', 'Merkez', 'Varto'],
  'Nevsehir': ['Acigol', 'Avanos', 'Derinkuyu', 'Gulsehir', 'Hacibektas', 'Kozakli', 'Merkez', 'Urgup'],
  'Nigde': ['Altunhisar', 'Bor', 'Ciftlik', 'Camardi', 'Merkez', 'Ulukisla'],
  'Ordu': ['Akkus', 'Altinordu', 'Aybasti', 'Camas', 'Catalpinar', 'Caybasi', 'Fatsa', 'Golkoy', 'Gulyali', 'Gurgentepe', 'Ikizce', 'Kabaduz', 'Kabatas', 'Korgan', 'Kumru', 'Mesudiye', 'Persembe', 'Ulubey', 'Unye'],
  'Osmaniye': ['Bahce', 'Duzici', 'Hasanbeyli', 'Kadirli', 'Merkez', 'Sumbas', 'Toprakkale'],
  'Rize': ['Ardesen', 'Camlihemsin', 'Cayeli', 'Derepazari', 'Findikli', 'Guneysu', 'Hemsin', 'Ikizdere', 'Iyidere', 'Kalkandere', 'Merkez', 'Pazar'],
  'Sakarya': ['Adapazari', 'Akyazi', 'Arifiye', 'Erenler', 'Ferizli', 'Geyve', 'Hendek', 'Karapurcek', 'Karasu', 'Kaynarca', 'Kocaali', 'Pamukova', 'Sapanca', 'Serdivan', 'Sogutlu', 'Tarakli'],
  'Samsun': ['19 Mayis', 'Alaçam', 'Asarcik', 'Atakum', 'Ayvacik', 'Bafra', 'Canik', 'Carsamba', 'Havza', 'Ilkadim', 'Kavak', 'Ladik', 'Salipazari', 'Tekkekoy', 'Terme', 'Vezirkopru', 'Yakakent'],
  'Sanliurfa': ['Akcakale', 'Birecik', 'Bozova', 'Ceylanpinar', 'Eyyubiye', 'Halfeti', 'Haliliye', 'Harran', 'Hilvan', 'Karakopru', 'Siverek', 'Suruc', 'Viransehir'],
  'Siirt': ['Baykan', 'Eruh', 'Kurtalan', 'Merkez', 'Pervari', 'Sirvan', 'Tillo'],
  'Sinop': ['Ayancik', 'Boyabat', 'Dikmen', 'Duragan', 'Erfelek', 'Gerze', 'Merkez', 'Sarayduzu', 'Turkeli'],
  'Sivas': ['Akincilar', 'Altinyayla', 'Divrigi', 'Dogansar', 'Gemerek', 'Golova', 'Gurun', 'Hafik', 'Imranli', 'Kangal', 'Koyulhisar', 'Merkez', 'Susehri', 'Sarkisla', 'Ulas', 'Yildizeli', 'Zara'],
  'Sirnak': ['Beytussebap', 'Cizre', 'Gucle', 'Idil', 'Merkez', 'Silopi', 'Uludere'],
  'Tekirdag': ['Cerkezkoy', 'Corlu', 'Ergene', 'Hayrabolu', 'Kapakli', 'Malkara', 'Marmaraereglisi', 'Muratli', 'Saray', 'Suleymanpasa', 'Sarkoy'],
  'Tokat': ['Almus', 'Artova', 'Basciftlik', 'Erbaa', 'Merkez', 'Niksar', 'Pazar', 'Resadiye', 'Sulusaray', 'Turhal', 'Yesilyurt', 'Zile'],
  'Trabzon': ['Akcaabat', 'Arakli', 'Arsin', 'Besikduzu', 'Caykara', 'Carsibasi', 'Dernekpazari', 'Duzkoy', 'Hayrat', 'Koprubasi', 'Macka', 'Of', 'Ortahisar', 'Surmene', 'Salpazari', 'Tonya', 'Vakfikebir', 'Yomra'],
  'Tunceli': ['Cemisgezek', 'Hozat', 'Mazgirt', 'Merkez', 'Nazimiye', 'Ovacik', 'Pertek', 'Pulumur'],
  'Usak': ['Banaz', 'Esme', 'Karahalli', 'Merkez', 'Sivasli', 'Ulubey'],
  'Van': ['Bahcesaray', 'Baskale', 'Caldiran', 'Catak', 'Edremit', 'Ercis', 'Gevas', 'Gurpinar', 'Ipekyolu', 'Muradiye', 'Ozalp', 'Saray', 'Tusba'],
  'Yalova': ['Altinova', 'Armutlu', 'Ciftlikkoy', 'Cinarcik', 'Merkez', 'Termal'],
  'Yozgat': ['Akdagmadeni', 'Aydincik', 'Bogazliyan', 'Candır', 'Cayiralan', 'Cekerek', 'Kadisehri', 'Merkez', 'Saraykent', 'Sarıkaya', 'Sorgun', 'Sefaatli', 'Yenifakili', 'Yerkoy'],
  'Zonguldak': ['Alapli', 'Caycuma', 'Devrek', 'Eregli', 'Gokcebey', 'Kilimli', 'Kozlu', 'Merkez'],
}

export const turkiyeProvinces = ['Mugla', ...Object.keys(turkiyeProvinceDistricts).filter(province => province !== 'Mugla')]

export function districtsForProvince(province: string) {
  return turkiyeProvinceDistricts[province] ?? []
}
